version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: verse-report-db
    environment:
      POSTGRES_USER: verse_user
      POSTGRES_PASSWORD: verse_password
      POSTGRES_DB: verse_report
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: